[package]
name = "rustynzb"
version = "0.1.0"
authors = ["tbess <tdbgamer@gmail.com>"]

[lib]
name = "rustynzb"
path = "src/lib.rs"

[dependencies]
quick-xml = "0.10.0"
failure = "0.1.1"
log = "0.4.1"
env_logger = "0.5.5"
